# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  # lane :beta do
  #   build_app(scheme: "iOSFastlane")
  #   upload_to_testflight
  # end

  lane :test do | options | 
    puts 'hello world'
    puts 'iam goint to clear derived data'
    clear_derived_data
  end

  lane :buildApp do | options | 
    # gym(scheme: "iOSFastlane")
    # Dir.chdir
    # Dir.chdir("/Users/kelly/Source/iOS/")
    sh 'pwd'
    # xcodebuild(
    #   archive: false,
    #   archive_path: "./build-dir/iOSFastlane.xcarchive",
    #   scheme: "iOSFastlane",
    #   workspace: "iOSFastlane.xcodeproj"
    # )
    xcbuild

  end
end
